### ISSUE TITLE
[Interpreter] UnboundLocalError on TBSmartTestSuite creation

### ISSUE THREAD

**Issue by S41nz** [S41nz/TBTAF#16]
Hi guys,

  Using the following statement:

//Replace TEST_CONTENT_LOCATION by the actual location on the repo for the test TBTestCases
myTestSuite = create_test_suite("C:\\Users\\psainza\\Documents\\TBTAF\\TBTAF\\tbtaf\\test\\discoverer\\samples",["TBTAF"])
//After the command above the following output on console is expected:
// For each discovered test
// Test <Test ID> loaded from: <Complete test filepath>
// Then at the end:
// Test suite created with <number of loaded tests> test cases

I got the following output:

Traceback (most recent call last):
  File "C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\tbtaf_launcher.py", line 17, in <module>
    parseResult = myTBTAF.parseScript(testScript)
  File "C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\orchestrator\TBTAFOrchestrator.py", line 62, in parseScript
    return _interpreter.parseScript(filePath)
  File "C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\interpreter\TBTAFInterpreter.py", line 116, in parseScript
    raise e
UnboundLocalError: local variable '_testSuite' referenced before assignment

Please check.

Thanks and regards

**Comment by S41nz** [comment]
Please refresh the code to the tip as I introduced another fix within TBSmartTestSuite.

Thanks

**Comment by carofermin** [comment]
Hello!

The issue is: 

File "C:\Users\Carolina\Dropbox\TBTAF\tbtaf\interpreter\TBTAFOrchestrator.py", line 114, in createTestSuite
    filteredTestCases = _testSuite.getTestCases(tagList, TBTAFFilterType.IN)
UnboundLocalError: local variable '_testSuite' referenced before assignment

**Comment by erflogo** [comment]
Fixed. Replaced _testSuite by _smartTestSuite.
