### ISSUE TITLE
[Executor] An exception caused by a wrong TBTestCase implementation should not crash the entire execution

### ISSUE THREAD

**Issue by S41nz** [S41nz/TBTAF#19]
Hi,

  While testing test03 script during the execution of the test cases I came to have the following output:

Cleanup performed from TestCompleteAndValidMetadata
Cleanup performed from TestOnlyRequiredMetadata
Cleanup performed from TestPriorityAboveLimit
Cleanup performed from TestPriorityBelowLimit
Cleanup performed from TestVerdictIsFail
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\executor\ExecutionTBTestSuite.py", line 63, in executionThread
    test.getResult().setStartTimestamp(datetime.datetime.now())
AttributeError: 'NoneType' object has no attribute 'setStartTimestamp'

Traceback (most recent call last):

  File "C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\tbtaf_launcher.py", line 17, in <module>
    parseResult = myTBTAF.parseScript(testScript)
  File "C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\orchestrator\TBTAFOrchestrator.py", line 62, in parseScript
    return _interpreter.parseScript(filePath)
  File "C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\interpreter\TBTAFInterpreter.py", line 116, in parseScript
    raise e
AttributeError: 'TestPriorityAboveLimit' object has no attribute 'testResult'

The root cause of the error here is that the TestPriorityAboveLimit does not have the result object initialized, which has to be corrected. However, the point here is that the entire application crashed. So here if an unexpected error occurs during the execution of a specific test, then an error should be logged on console and the execution of that specific test should be aborted while continuing with the rest of the tests.

Thanks and regards

**Comment by JuanCalvilloTec** [comment]
Fix merged.
