### ISSUE TITLE
[Orchestrator] Import error in TBTAFOrchestrator

### ISSUE THREAD

**Issue by S41nz** [S41nz/TBTAF#3]
Traceback (most recent call last):
  File "C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\test\tbtaf_test_bed.py", line 6, in <module>
    from orchestrator import TBTAFOrchestrator
  File "C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\orchestrator\TBTAFOrchestrator.py", line 20, in <module>
    from interpreter.interpreter import TBInterpreter
ImportError: No module named interpreter

**Comment by erflogo** [comment]
Fixing import from Interpreter. The file is called TBTAFInterpreter.py.
